name: cjmshimlaparent
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.17+17

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^6.1.2
  scrollable_clean_calendar: ^1.5.0
  google_fonts: ^6.2.1
  carousel_slider_plus: ^7.1.0
  table_calendar: ^3.0.9
  intl: ^0.18.0
  html: ^0.15.0 # Check for the latest version
  url_launcher: ^6.0.20 # Use the latest version
  video_player: ^2.5.1
  youtube_player_flutter: ^8.1.1
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^2.0.12
  firebase_messaging: ^15.1.0
  firebase_core: ^3.4.0
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  fluttertoast: ^8.2.8
  encrypt: ^5.0.1
  crypto: ^3.0.2
#  flutter_inappwebview: ^5.7.2+3
  syncfusion_flutter_datepicker: ^24.2.6
  flutter_screenutil: ^5.9.0
  day_picker: ^2.3.0
  cached_network_image: ^3.4.0
  animated_custom_dropdown: ^3.1.1
  flutter_searchable_dropdown: ^2.0.0
  dropdown_search: ^5.0.6
  searchable_paginated_dropdown: ^1.3.0
  open_filex: ^4.6.0
  permission_handler: ^11.3.1
  pdf: ^3.11.3
  dropdown_button2: ^2.3.9
  package_info_plus: ^8.0.2
  pin_code_fields: ^8.0.1
  upgrader: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter_icons:
  android: true
  image_path: "assets/app_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.png
    - assets/aipay_uat.html
    - assets/aipay_prod.html
